name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Restore artifacts, or setup vcpkg (do not install any package)
      uses: AndreiTurean/template_cmake_library@main
    - uses: actions/checkout@main
